"""add evidence_clips table

Revision ID: 88cea65705d0
Revises: 53bf749fb602
Create Date: 2026-09-23 00:28:40.247075

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88cea65705d0"
down_revision: str | Sequence[str] | None = "53bf749fb602"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_clips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, comment="pending | sealed | failed"),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("sha256", sa.String(), nullable=True),
        sa.Column("manifest", sa.JSON(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["camera_id"], ["cameras.camera_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_clips_alert_id"), "evidence_clips", ["alert_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_clips_alert_id"), table_name="evidence_clips")
    op.drop_table("evidence_clips")
    # ### end Alembic commands ###
