"""add detections, watchlist, alerts, camera health

Revision ID: bb61c03e722f
Revises: f8e31a6ef376
Create Date: 2026-09-22 16:24:17.283391

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb61c03e722f'
down_revision: str | Sequence[str] | None = 'f8e31a6ef376'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_normalised', sa.String(), nullable=False),
    sa.Column('plate_ambiguity_key', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False, comment='stolen | wanted | missing | suspect | bolo'),
    sa.Column('priority', sa.String(), nullable=False, comment='low | medium | high | critical'),
    sa.Column('case_reference', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True, comment='Expired entries stop matching automatically — purpose limitation, not just a UI filter'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_entries_plate_ambiguity_key'), 'watchlist_entries', ['plate_ambiguity_key'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_plate_normalised'), 'watchlist_entries', ['plate_normalised'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_entry_id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('detection_event_id', sa.String(), nullable=False),
    sa.Column('plate_text', sa.String(), nullable=False),
    sa.Column('match_rung', sa.String(), nullable=False, comment='exact | ambiguity_class'),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, comment='new | acknowledged | assigned | in_progress | resolved | false_positive'),
    sa.Column('sighting_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_entry_id'], ['watchlist_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('plate_text', sa.String(), nullable=False),
    sa.Column('plate_normalised', sa.String(), nullable=False),
    sa.Column('plate_ambiguity_key', sa.String(), nullable=False),
    sa.Column('plate_confidence', sa.Float(), nullable=False),
    sa.Column('format_valid', sa.Boolean(), nullable=False),
    sa.Column('frames_voted', sa.Integer(), nullable=False),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('vehicle_track_id', sa.String(), nullable=True),
    sa.Column('bbox_x', sa.Integer(), nullable=True),
    sa.Column('bbox_y', sa.Integer(), nullable=True),
    sa.Column('bbox_width', sa.Integer(), nullable=True),
    sa.Column('bbox_height', sa.Integer(), nullable=True),
    sa.Column('pts_ms', sa.Float(), nullable=False),
    sa.Column('snapshot_uri', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('model_versions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'observed_at'),
    sa.UniqueConstraint('event_id', 'observed_at', name='uq_detection_event')
    )
    op.create_index(op.f('ix_detections_observed_at'), 'detections', ['observed_at'], unique=False)
    op.create_index(op.f('ix_detections_plate_ambiguity_key'), 'detections', ['plate_ambiguity_key'], unique=False)
    op.create_index(op.f('ix_detections_plate_normalised'), 'detections', ['plate_normalised'], unique=False)
    op.add_column('cameras', sa.Column('measured_fps', sa.Float(), nullable=True, comment='Derived from PTS by the edge worker — never the declared rate'))
    op.add_column('cameras', sa.Column('declared_fps', sa.Float(), nullable=True))
    op.add_column('cameras', sa.Column('reconnects', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('cameras', sa.Column('discontinuities', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

    # TimescaleDB hypertable: SQLAlchemy has no native construct for this, so
    # it is not part of autogenerate's diff and must be added by hand, once,
    # right after the table it applies to is created. observed_at (derived
    # from stream_epoch + PTS, never arrival time) is the partitioning
    # column — see the Detection model's docstring. Requires observed_at to
    # be part of the primary key (already composite above), or PostgreSQL
    # refuses with "cannot create a unique index without the partitioning
    # column" — hit and fixed while building this.
    op.execute("SELECT create_hypertable('detections', 'observed_at')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'discontinuities')
    op.drop_column('cameras', 'reconnects')
    op.drop_column('cameras', 'declared_fps')
    op.drop_column('cameras', 'measured_fps')
    op.drop_index(op.f('ix_detections_plate_normalised'), table_name='detections')
    op.drop_index(op.f('ix_detections_plate_ambiguity_key'), table_name='detections')
    op.drop_index(op.f('ix_detections_observed_at'), table_name='detections')
    op.drop_table('detections')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_watchlist_entries_plate_normalised'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_plate_ambiguity_key'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    # ### end Alembic commands ###
