"""add field_sighting_reports table

Revision ID: bc2e193d6030
Revises: 88cea65705d0
Create Date: 2026-09-23 07:55:16.108811

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc2e193d6030"
down_revision: str | Sequence[str] | None = "88cea65705d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "field_sighting_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_report_id", sa.String(), nullable=False),
        sa.Column("reported_by", sa.String(), nullable=False),
        sa.Column("plate_text", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("photo_path", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_sighting_reports_client_report_id"),
        "field_sighting_reports",
        ["client_report_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_field_sighting_reports_client_report_id"), table_name="field_sighting_reports"
    )
    op.drop_table("field_sighting_reports")
    # ### end Alembic commands ###
