"""Coverage gap analysis — a real coverage-shape query, not dots on a map.

MVP approximation, documented honestly: cells are generated by PostGIS's
`ST_SquareGrid` in degree-space (SRID 4326) over the bounding box of
registered cameras, using a cell size converted from metres via the
`cell_size_m`/111,320 approximation and the camera set's mean latitude for
the longitude correction. This is adequate for "where are the coverage
holes" at a district/state scale; it is not survey-grade geodesy, and does
not (yet) account for terrain, buildings, or a camera's actual field of view
beyond a simple radius — the `fov` polygon column exists on `Camera` for a
future, more precise version of this query.
"""

from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from core_api.registry.schemas import CoverageGapReport, GapCell, GeoPointOut

__all__ = ["compute_coverage_gaps"]

_METRES_PER_DEGREE_LAT = 111_320.0


@dataclass(slots=True)
class _Bounds:
    min_lon: float
    min_lat: float
    max_lon: float
    max_lat: float
    mean_lat: float


async def _camera_bounds(session: AsyncSession, margin_m: float) -> _Bounds | None:
    result = await session.execute(
        text(
            """
            SELECT
                ST_XMin(ST_Extent(location)) AS min_lon,
                ST_YMin(ST_Extent(location)) AS min_lat,
                ST_XMax(ST_Extent(location)) AS max_lon,
                ST_YMax(ST_Extent(location)) AS max_lat,
                AVG(ST_Y(location)) AS mean_lat
            FROM cameras
            WHERE location IS NOT NULL
            """
        )
    )
    row = result.one_or_none()
    if row is None or row.min_lon is None:
        return None

    margin_deg_lat = margin_m / _METRES_PER_DEGREE_LAT
    return _Bounds(
        min_lon=row.min_lon - margin_deg_lat,
        min_lat=row.min_lat - margin_deg_lat,
        max_lon=row.max_lon + margin_deg_lat,
        max_lat=row.max_lat + margin_deg_lat,
        mean_lat=row.mean_lat,
    )


async def compute_coverage_gaps(
    session: AsyncSession,
    *,
    coverage_radius_m: float = 500.0,
    cell_size_m: float = 250.0,
    margin_m: float = 1_000.0,
) -> CoverageGapReport:
    """For every cell in a grid spanning the registered cameras (+ margin),
    report whether it has a camera within `coverage_radius_m` — and if so,
    which one and how far. Cameras with no location are excluded (they
    cannot contribute to a spatial coverage claim)."""
    bounds = await _camera_bounds(session, margin_m)
    if bounds is None:
        return CoverageGapReport(
            total_cells=0,
            covered_cells=0,
            uncovered_cells=0,
            coverage_radius_m=coverage_radius_m,
            cell_size_m=cell_size_m,
            cells=[],
        )

    import math

    lon_correction = math.cos(math.radians(bounds.mean_lat)) or 1e-6
    cell_size_deg_lat = cell_size_m / _METRES_PER_DEGREE_LAT
    # ST_SquareGrid takes one size for both axes; using the latitude-based
    # size for both keeps cells roughly square in metres near mean_lat, at
    # the cost of some distortion away from it — acceptable for this MVP.

    result = await session.execute(
        text(
            """
            WITH bounds AS (
                SELECT ST_MakeEnvelope(:min_lon, :min_lat, :max_lon, :max_lat, 4326) AS envelope
            ),
            grid AS (
                SELECT (ST_SquareGrid(:cell_size, envelope)).geom AS cell
                FROM bounds
            ),
            centers AS (
                SELECT ST_Centroid(cell) AS center FROM grid
            )
            SELECT
                ST_X(centers.center) AS lon,
                ST_Y(centers.center) AS lat,
                nearest.camera_id AS nearest_camera_id,
                nearest.distance_m AS nearest_distance_m
            FROM centers
            LEFT JOIN LATERAL (
                SELECT
                    c.camera_id,
                    ST_Distance(c.location::geography, centers.center::geography) AS distance_m
                FROM cameras c
                WHERE c.location IS NOT NULL
                ORDER BY c.location::geography <-> centers.center::geography
                LIMIT 1
            ) AS nearest ON true
            """
        ),
        {
            "min_lon": bounds.min_lon,
            "min_lat": bounds.min_lat,
            "max_lon": bounds.max_lon,
            "max_lat": bounds.max_lat,
            "cell_size": cell_size_deg_lat / lon_correction,
        },
    )

    cells = [
        GapCell(
            center=GeoPointOut(lat=row.lat, lon=row.lon),
            covered=(
                row.nearest_distance_m is not None and row.nearest_distance_m <= coverage_radius_m
            ),
            nearest_camera_id=row.nearest_camera_id,
            nearest_camera_distance_m=row.nearest_distance_m,
        )
        for row in result.all()
    ]
    covered = sum(1 for c in cells if c.covered)

    return CoverageGapReport(
        total_cells=len(cells),
        covered_cells=covered,
        uncovered_cells=len(cells) - covered,
        coverage_radius_m=coverage_radius_m,
        cell_size_m=cell_size_m,
        cells=cells,
    )
